'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに失われたりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Register

    '''<summary>
    '''RegisterUser コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナー ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents RegisterUser As Global.System.Web.UI.WebControls.CreateUserWizard

    '''<summary>
    '''RegisterUserWizardStep コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナー ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents RegisterUserWizardStep As Global.System.Web.UI.WebControls.CreateUserWizardStep
End Class
